import os
from utils.new_utils import call_model
import asyncio
from typing import List
import json
from utils.utils import get_diagnosis, gpt_parse
import re
from typing import Dict

_SYMPTOM_DIAG_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "data", "symptom-diag.json",
)


def extract_diagnosis(response: str) -> str:
    pattern = r"<diagnosis>(.*?)</diagnosis>"
    match = re.search(pattern, response)
    if match:
        return match.group(1)
    else:
        return ""


_symptoms = "Chest Pain, Dyspnea (Shortness of Breath), Abdominal Pain, Headache, Altered Mental Status/Confusion, Fever, Back Pain, Syncome/Near Syncope, Palpitations, Dizziness/Vertigo, Nausea/Vomiting, Weakness/Fatigue, Seizures, Sore Throat/Difficulty Swallowing, Extremity Pain/Swelling"


class WarningAgent:
    """
    Agent to generate warning diagnosis that should not be missed for the case description.
    """

    def __init__(
        self, model: str, llm_provider: str = "openai"
    ):
        self.model = model
        self.api_key = os.environ.get("OPENAI_API_KEY", "")
        with open(_SYMPTOM_DIAG_PATH) as _f:
            self.warning_diagnosis = json.load(_f)
        self.llm_provider = llm_provider

    def _free_warning_messages(
        self, case_description: str, exclude_diagnoses: List[str] | None = None
    ) -> List[Dict]:
        exclude_block = ""
        if exclude_diagnoses:
            exclude_block = (
                "\n        The following diagnoses have ALREADY been established as the "
                "primary differential and MUST NOT be repeated in your output "
                "(neither the same wording nor a clinical synonym): "
                f"{exclude_diagnoses}."
            )
        query = f"""For this patient's case, identify up to 5 diagnoses that must not be missed.
        Focus on life-threatening or time-sensitive conditions relevant to the presentation.{exclude_block}
        You must return ONLY a JSON list, each item with keys: 'warning_diagnosis' (str) and 'reason' (str).
        The case description is: {case_description}"""
        return [{"role": "user", "content": query}]

    def _merge_warning_messages(
        self, case_description: str, symptom_candidates: List[str], free_candidates: List[str],
        exclude_diagnoses: List[str] | None = None,
    ) -> List[Dict]:
        exclude_block = ""
        if exclude_diagnoses:
            exclude_block = (
                "\n        HARD CONSTRAINT: The following diagnoses are already part of the "
                "primary differential and MUST NOT appear in the Top-3 warning list — not "
                "verbatim, not as clinical synonyms, and not as broader/narrower phrasings "
                f"of the same condition: {exclude_diagnoses}. "
                "Drop any candidate that overlaps and pick the next-best must-not-miss "
                "diagnosis instead."
            )
        query = f"""You are given two lists of must-not-miss diagnoses for a patient case, generated by different methods.
        Evaluate all candidates together and select the Top-3 final warning diagnoses most relevant to this specific case.
        Rank them by clinical urgency and likelihood given the case.{exclude_block}
        You must return ONLY a JSON list of exactly 3 items, each with keys: 'warning_diagnosis' (str) and 'reason' (str).
        The output format must be:
        [
            {{"warning_diagnosis": "...", "reason": "..."}},
            {{"warning_diagnosis": "...", "reason": "..."}},
            {{"warning_diagnosis": "...", "reason": "..."}}
        ]
        Case description: {case_description}
        Symptom-lookup candidates: {symptom_candidates}
        Free-generation candidates: {free_candidates}
        Top-3 warning diagnoses:"""
        return [{"role": "user", "content": query}]

    def _warning_diagnosis_messages(
        self, case_description: str, diagnosis_dict: Dict[str, List[str]]
    ) -> List[Dict]:
        query = f"""For this patient's case, please provide the Top-3 warning diagnoses that should not be missed.
        The results should rank the warning diagnoses by the importance of the warning diagnosis.
        All warning diagnoses must be in the following diagnosis dict: {diagnosis_dict}.
        You must return ONLY json objects, with the key: 'warning_diagnosis' (str) and 'reason' (str).
        The reason should be a short description why warning diagnosis should not be missed.
        The output format must be:
        [
            {{"warning_diagnosis": "warning diagnosis 1", "reason": "reason 1"}},
            {{"warning_diagnosis": "warning diagnosis 2", "reason": "reason 2"}},
            {{"warning_diagnosis": "warning diagnosis 3", "reason": "reason 3"}},
        ]
        For the case description: {case_description}
        The Top-3 warning diagnoses are:
        """
        messages = [{"role": "user", "content": query}]
        return messages

    def _symptom_extraction_messages(self, case_description: str) -> str:
        query = f"""For this patient's case, extract the symptoms in this case. 
        You must return ONLY a list of json objects, with the key: 'symptom' (str).'
        Each symptom must be in the following list: {_symptoms}. Donot change the symptom name. Donot add any other words.
        The case description is: {case_description}"""
        messages = [{"role": "user", "content": query}]
        return messages

    def _additional_warning_diagnosis_messages(
        self, case_description: str, diagnosis_list: List[str]
    ) -> str:
        query = f"""Please analyze this patient's case and provide one possible diagnosis result. The diagnosis should be different from the previous diagnoses and should be related to the case description. You must return ONLY a JSON object, with the key: 'analysis' (str), 'diagnosis' (str).'
        The case description is: {case_description}
        The previous diagnoses are: {diagnosis_list}"""
        messages = [{"role": "user", "content": query}]
        return messages

    async def symptom_extraction(self, case_description: str) -> str:
        messages = self._symptom_extraction_messages(case_description)
        result = await call_model(
            messages,
            self.model,
            temperature=0.7,
            response_format="json",
            llm_provider=self.llm_provider,
        )
        symptoms = [d["symptom"] for d in result]
        return symptoms

    def get_warning_diagnosis(self, symptoms: List[str]) -> str:
        warning_diagnosis = {}
        for symptom in symptoms:
            try:
                warning_diagnosis[symptom.strip()] = self.warning_diagnosis[symptom.strip()]
            except KeyError:
                # warning_diagnosis[symptom.strip()] = []
                print(f"Symptom {symptom.strip()} not found in warning diagnosis")
                continue
        return warning_diagnosis

    async def _free_warning_generation(
        self, case_description: str, exclude_diagnoses: List[str] | None = None
    ) -> List[str]:
        messages = self._free_warning_messages(case_description, exclude_diagnoses)
        result = await call_model(
            messages,
            self.model,
            temperature=0.7,
            response_format="json",
            llm_provider=self.llm_provider,
        )
        return [d["warning_diagnosis"] for d in result]

    async def diagnose(
        self, case_description: str, exclude_diagnoses: List[str] | None = None
    ) -> List[Dict]:
        """Produce Top-3 must-not-miss diagnoses.

        If ``exclude_diagnoses`` is provided (e.g. the settled primary
        differential), the free-generation prompt and the merge prompt are both
        constrained to skip anything that overlaps with that list — verbatim
        matches and clinical synonyms alike.
        """
        # Step 1: run free generation and symptom extraction in parallel
        free_list, symptoms = await asyncio.gather(
            self._free_warning_generation(case_description, exclude_diagnoses),
            self.symptom_extraction(case_description),
        )

        # Step 2: symptom-dict lookup
        diagnosis_dict = self.get_warning_diagnosis(symptoms)
        symptom_list = [d for diags in diagnosis_dict.values() for d in diags]

        # Step 3: merge both lists and re-rank to final Top-3, again excluding
        # anything already in the primary differential.
        messages = self._merge_warning_messages(
            case_description, symptom_list, free_list, exclude_diagnoses
        )
        results = await call_model(
            messages,
            self.model,
            temperature=0.3,
            response_format="json",
            llm_provider=self.llm_provider,
        )
        return results

    async def additional_diagnosis(
        self, case_description: str, diagnosis_list: List[str]
    ) -> str:
        messages = self._additional_warning_diagnosis_messages(
            case_description, diagnosis_list
        )
        result = await call_model(
            messages,
            self.model,
            temperature=0.5,
            response_format="json",
            llm_provider=self.llm_provider,
        )
        return result
